backend:
  name: turbo-github
  turbo_site_id: 39869a1f-8212-4705-8ea1-59c0611a60c2
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:

  - name: "settings"
    label: "Website Settings"
    files:
      - label: "Website Settings"
        name: "settings"
        file: "site-settings.json"
        format: "json"
        fields:
          - label: "Hero Title"
            name: "heroTitle"
            widget: "string"

          - label: "Hero Subtitle"
            name: "heroSubtitle"
            widget: "text"

          - label: "Hero Button Text"
            name: "heroButtonText"
            widget: "string"

          - label: "Hero Button Link"
            name: "heroButtonLink"
            widget: "string"

          - label: "Pinterest Button Text"
            name: "pinterestButtonText"
            widget: "string"

          - label: "Pinterest Button Link"
            name: "pinterestButtonLink"
            widget: "string"

          - label: "Products Title"
            name: "productsTitle"
            widget: "string"

          - label: "Products Subtitle"
            name: "productsSubtitle"
            widget: "text"

          - label: "Footer Text"
            name: "footerText"
            widget: "string"

  - name: "products"
    label: "Products"
    files:
      - label: "Products"
        name: "products"
        file: "products.json"
        format: "json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"

              - label: "Category"
                name: "category"
                widget: "string"

              - label: "Price"
                name: "price"
                widget: "string"

              - label: "Description"
                name: "description"
                widget: "text"

              - label: "Image"
                name: "image"
                widget: "image"

              - label: "Affiliate Link"
                name: "link"
                widget: "string"

  - name: "categories"
    label: "Categories"
    files:
      - label: "Categories"
        name: "categories"
        file: "categories.json"
        format: "json"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"

              - label: "Number"
                name: "number"
                widget: "string"
