backend:
  name: turbo-github
  turbo_site_id: 39869a1f-8212-4705-8ea1-59c0611a60c2
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "products"
    label: "Products"
    files:
      - label: "Products"
        name: "products"
        file: "products.json"
        format: "json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - label: "Name"
                name: "name"
                widget: "string"

              - label: "Category"
                name: "category"
                widget: "string"

              - label: "Price"
                name: "price"
                widget: "string"

              - label: "Description"
                name: "description"
                widget: "text"

              - label: "Image"
                name: "image"
                widget: "image"

              - label: "Affiliate Link"
                name: "link"
                widget: "string"
